### ISSUE TITLE
Dead Links #2

### ISSUE THREAD

**Issue by kagura-maru** [The-Hacker-Recipes/The-Hacker-Recipes#108]
Navigating from https://www.thehacker.recipes/ad/movement/builtins/security-groups to read on Backup Operators with these two broken link giving 404:

https://www.thehacker.recipes/ad/movement/credentials/dumping/sam-and-lsa-secrets.md
https://www.thehacker.recipes/ad/movement/credentials/dumping/dcsync.md

**Comment by ShutdownRepo** [comment]
Thank you for reporting the issue, it should be fixed soon

**Comment by AzeTIIx** [comment]
Fixed #112 , thank you for reporting :)
