### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by MegaAppster** [The-Hacker-Recipes/The-Hacker-Recipes#93]
Root-Me links to this non existent page. 

https://www.thehacker.recipes/ad-ds/movement/credentials/cracking

**Comment by ShutdownRepo** [comment]
indeed, the correct link should be https://www.thehacker.recipes/ad/movement/credentials/cracking 
Added a dynamic redirect in #99 
Will be fixed in prod shortly if not already. It's fixed in the pre-prod ✅
Thank you for reporting the deadlink 👍
